name: CI
on:
  push:
    #branches:
    #  - main
    #  - bugfix/**
    #  - feature/**
    tags:
      - 'release-v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  publish:
    name: Publish action
    runs-on: windows-latest
    
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2.5.0    
    - name: Publish Module to PowerShell Gallery
      #uses: pcgeek86/publish-powershell-module-action@v20
      env:
          API_KEY: ${{ secrets.PS_GALLERY_KEY }}
      id: publish-module
      run: |
        Publish-Module -Path "$env:GITHUB_WORKSPACE" -NuGetApiKey $env:API_KEY
